stages:
  - build-and-test
  - benchmark

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse/eclipse
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  ANT: "ant -e"

before_script:
  - (cd core-lib && git remote add smarr https://github.com/smarr/SOM.git || true; git fetch --all)
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - ${ANT} tests native-obj-storage-test native-tests
    - ./som -G -cp core-lib/Smalltalk:core-lib/TestSuite:core-lib/SomSom/src/compiler:core-lib/SomSom/src/vm:core-lib/SomSom/src/vmobjects:core-lib/SomSom/src/interpreter:core-lib/SomSom/src/primitives core-lib/SomSom/tests/SomSomTests.som

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ${ANT} compile native-ast -Dno.jit=true
    - ${ANT} compile native-bc  -Dno.jit=true
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
